version: '3'

services:
  db:
    image: postgres:15.3
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin123'
      POSTGRES_DB: 'pemid_link'
    container_name: pemid_link_db
    volumes:
      - ./postgres:/var/lib/postgresql/data